[main]
#plugins=ifupdown,keyfile
plugins=keyfile
dns=default

[keyfile]
unmanaged-devices=none
#[ifupdown]
#managed=true

[device]
wifi.scan-rand-mac-address=yes

[device]
match-device=interface-name:wlan0
managed=1
