TARGET_ARCH="arm"
TUNE_ARCH="arm"
PREFERRED_PROVIDER_virtual/kernel ??= "linux-armadillo-g3"
PREFERRED_PROVIDER_virtual/bootloader ??= "u-boot-armadillo-g3"
MACHINE_FEATURES = "pci ext3 serial wifi"
MACHINE_EXTRA_RRECOMMENDS += " kernel-modules"
KERNEL_CLASSES += "kernel-fitimage"
KERNEL_DEVICETREE = "armadillo_iotg_g3_m1.dtb"
KERNEL_IMAGETYPE = "fitImage"
UBOOT_MACHINE = "x1_config"
UBOOT_BINARY = "u-boot-x1.bin"
require conf/machine/include/tune-armadillo-g3.inc
